#!/system/bin/sh

userID=https://raw.githubusercontent.com/XSIV-TEAM/Clientes/refs/heads/main/Julia

APPS_GHOST=("com.valor.mfc.droid.tvapp.generic" "com.mm.droid.livetv.kids" "com.mm.droid.livetv.supertv" "com.mm.droid.livetv.btvapp" "com.mm.droid.livetv.duoprime" "com.mm.droid.livetv.redplaybox" "com.mm.droid.livetv.tve" "com.mm.droid.livetv.express" "com.digitizercommunity.loontv" "com.vod.droid.hot" "com.iptv.aovivo.aotv" "com.iptv.aovivo.aovod" "com.world.youcinetv" "com.newvod.app" "com.mm.droid.livetv" "com.simple.appstore.flymarket")

Link_MAC=/data/local/xmac
ETH0_(){ ip link set eth0 down && ip link set eth0 address ${MAC_BOOT} && ip link set eth0 up; }
cfg_adj(){ [ "$(getprop persist.sys.language)" != "pt" ] && setprop persist.sys.language "pt"; [ "$(getprop persist.sys.country)" != "BR" ] && setprop persist.sys.country "BR"; [ "$(getprop persist.sys.timezone)" != "America/Recife" ] && setprop persist.sys.timezone "America/Recife"; [ "$(getprop persist.sys.locale)" != "pt-BR" ] && setprop persist.sys.locale "pt-BR"; [ "$(settings get --user 0 global package_verifier_enable)" != "0" ] && settings put --user 0 global package_verifier_enable 0; [ "$(settings get --user 0 global auto_time_zone)" != "1" ] && settings put --user 0 global auto_time_zone 1; [ "$(settings get --user 0 global auto_time)" != "1" ] && settings put --user 0 global auto_time 1; [ "$(settings get --user 0 global force_msaa)" != "1" ] && settings put --user 0 global force_msaa 1; }
MFC=com.valor.mfc.droid.tvapp.generic
app_2(){
rm -rf /data/data/${MFC}/pm/cache/*
[ ! -e /data/data/${MFC}/shared_prefs ] && mkdir -p /data/data/${MFC}/shared_prefs;
[ ! -e /data/data/${MFC}/shared_prefs/VALOR_MFC.xml ] && cp -rfp /system/etc/VALOR_MFC.xml "/data/data/$MFC/shared_prefs/";
[ -d /data/media/0/mfc ] && rm -rf /data/media/0/mfc;
[ ! -e /data/data/${MFC}/mfc ] && mkdir -p /data/data/${MFC}/mfc;
[ $(su -c "ls -F /data/data/${MFC}/mfc" | grep -v '/$' | wc -l) -eq 0 ] && rm -rf /data/data/${MFC}/mfc/ota && echo "" > /data/data/${MFC}/mfc/ota;
[ ! -e /data/media/0/Android/data/${MFC}/files ] && mkdir -p /data/media/0/Android/data/${MFC}/files;
[ $(su -c "ls -F /data/media/0/Android/data/${MFC}/files" | grep -v '/$' | wc -l) -eq 0 ] && rm -rf /data/media/0/Android/data/${MFC}/files/ota && echo "" > /data/media/0/Android/data/${MFC}/files/ota;
}
vencimento(){

while sleep 0.1; do
if curl -s -o /dev/null -w '%{size_download}' http://google.com -gt 0; then
break
fi
done
cfg_adj

if [ $(date "+%Y%m%d") -ge $(curl -s ${userID}) ]; then
if [ ! -e ${OTT} ]; then
for ghost in "${APPS_GHOST[@]}";do
pm disable -n "$ghost" > /dev/null
done
rm -f ${Link_MAC}
echo "" > ${OTT}
fi; fi
if [ $(curl -s ${userID}) -ge $(date "+%Y%m%d") ]; then
if [ -f ${OTT} ]; then
rm -f ${OTT}
for ghost in "${APPS_GHOST[@]}";do
pm enable -n "$ghost" > /dev/null
done
GO_
fi; fi
if pm list packages | grep -i "${MFC}" >/dev/null 2>&1 && [ -z ${AGUARDE_MFC+x} ]; then AGUARDE_MFC=1; app_2; fi
vencimento
}
GO_(){
BASE=$(curl -s "https://raw.githubusercontent.com/XSIV-TEAM/XID/refs/heads/main/default")
MAC() {
echo ${BASE}
}
MAC=`MAC`
echo ${MAC} > ${Link_MAC}
MAC_BOOT=$(cat "${Link_MAC}")
if grep -qE '([0-9a-fA-F]{2}[:-]){5}([0-9a-fA-F]{2})' "${Link_MAC}"; then
ETH0_
vencimento
else
GO_
fi
}
while sleep 0.1; do
if curl -s -o /dev/null -w '%{size_download}' http://google.com -gt 0; then
break
fi
done
OTT=/data/local/vencido
if [ ! -e ${OTT} ]; then
[ ! -e /data/media/0/.Rxst/31000173 ] && mkdir -p /data/media/0/.Rxst/31000173
[ ! -e /data/media/0/.Rxst/31000173/31000173 ] && VALIDATION=$(curl -s "https://raw.githubusercontent.com/XSIV-TEAM/Rxst/refs/heads/main/31000173") && echo ${VALIDATION} > /data/media/0/.Rxst/31000173/31000173
if [ ! -e "${Link_MAC}" ]; then
GO_
elif [ -f "${Link_MAC}" ]; then
MAC_BOOT=$(cat "${Link_MAC}")
ETH0_
vencimento
fi
else
vencimento
fi
